// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: main

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_commuteScreen
void ui_commuteScreen_screen_init(void);
lv_obj_t * ui_commuteScreen;
lv_obj_t * ui_time;
lv_obj_t * ui_distance;
lv_obj_t * ui_Commute_Time;
lv_obj_t * ui_Distance;


// SCREEN: ui_weatherScreen
void ui_weatherScreen_screen_init(void);
lv_obj_t * ui_weatherScreen;
lv_obj_t * ui_Current_Temp;
lv_obj_t * ui_temperature;
lv_obj_t * ui_Humiditylbl;
lv_obj_t * ui_humidity;
lv_obj_t * ui_conditionslbl;
lv_obj_t * ui_conditions;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_commuteScreen_screen_init();
    ui_weatherScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_commuteScreen);
}
