// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: main

#ifndef _MAIN_UI_H
#define _MAIN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_commuteScreen
void ui_commuteScreen_screen_init(void);
extern lv_obj_t * ui_commuteScreen;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_distance;
extern lv_obj_t * ui_Commute_Time;
extern lv_obj_t * ui_Distance;
// SCREEN: ui_weatherScreen
void ui_weatherScreen_screen_init(void);
extern lv_obj_t * ui_weatherScreen;
extern lv_obj_t * ui_Current_Temp;
extern lv_obj_t * ui_temperature;
extern lv_obj_t * ui_Humiditylbl;
extern lv_obj_t * ui_humidity;
extern lv_obj_t * ui_conditionslbl;
extern lv_obj_t * ui_conditions;
extern lv_obj_t * ui____initial_actions0;





void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
