// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: main

#include "../ui.h"

void ui_commuteScreen_screen_init(void)
{
    ui_commuteScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_commuteScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time = lv_label_create(ui_commuteScreen);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, 0);
    lv_obj_set_y(ui_time, -25);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "TIME");

    ui_distance = lv_label_create(ui_commuteScreen);
    lv_obj_set_width(ui_distance, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_distance, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_distance, 0);
    lv_obj_set_y(ui_distance, 45);
    lv_obj_set_align(ui_distance, LV_ALIGN_CENTER);
    lv_label_set_text(ui_distance, "DISTANCE");

    ui_Commute_Time = lv_label_create(ui_commuteScreen);
    lv_obj_set_width(ui_Commute_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Commute_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Commute_Time, 0);
    lv_obj_set_y(ui_Commute_Time, -45);
    lv_obj_set_align(ui_Commute_Time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Commute_Time, "Commute Time");

    ui_Distance = lv_label_create(ui_commuteScreen);
    lv_obj_set_width(ui_Distance, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Distance, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Distance, 0);
    lv_obj_set_y(ui_Distance, 25);
    lv_obj_set_align(ui_Distance, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Distance, "Distance:");

}
