// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: main

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, 0);
    lv_obj_set_y(ui_time, -25);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "TIME");

    ui_distance = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_distance, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_distance, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_distance, 0);
    lv_obj_set_y(ui_distance, 45);
    lv_obj_set_align(ui_distance, LV_ALIGN_CENTER);
    lv_label_set_text(ui_distance, "DISTANCE");

    ui_CommuteTime = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_CommuteTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CommuteTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CommuteTime, 0);
    lv_obj_set_y(ui_CommuteTime, -45);
    lv_obj_set_align(ui_CommuteTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CommuteTime, "Commute Time:");

    ui_ = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_, 0);
    lv_obj_set_y(ui_, 25);
    lv_obj_set_align(ui_, LV_ALIGN_CENTER);
    lv_label_set_text(ui_, "Distance:");

}
