// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: main

#include "../ui.h"

void ui_weatherScreen_screen_init(void)
{
    ui_weatherScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_weatherScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Current_Temp = lv_label_create(ui_weatherScreen);
    lv_obj_set_width(ui_Current_Temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Current_Temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Current_Temp, 0);
    lv_obj_set_y(ui_Current_Temp, -60);
    lv_obj_set_align(ui_Current_Temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Current_Temp, "Temperature");

    ui_temperature = lv_label_create(ui_weatherScreen);
    lv_obj_set_width(ui_temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperature, 0);
    lv_obj_set_y(ui_temperature, -40);
    lv_obj_set_align(ui_temperature, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_temperature, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_temperature, "TEMPERATURE");

    ui_Humiditylbl = lv_label_create(ui_weatherScreen);
    lv_obj_set_width(ui_Humiditylbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Humiditylbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Humiditylbl, 0);
    lv_obj_set_y(ui_Humiditylbl, -10);
    lv_obj_set_align(ui_Humiditylbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Humiditylbl, "Humidity:");

    ui_humidity = lv_label_create(ui_weatherScreen);
    lv_obj_set_width(ui_humidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humidity, 0);
    lv_obj_set_y(ui_humidity, 10);
    lv_obj_set_align(ui_humidity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humidity, "HUMIDITY");

    ui_conditionslbl = lv_label_create(ui_weatherScreen);
    lv_obj_set_width(ui_conditionslbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_conditionslbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_conditionslbl, 0);
    lv_obj_set_y(ui_conditionslbl, 40);
    lv_obj_set_align(ui_conditionslbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_conditionslbl, "Conditions:");

    ui_conditions = lv_label_create(ui_weatherScreen);
    lv_obj_set_width(ui_conditions, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_conditions, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_conditions, 0);
    lv_obj_set_y(ui_conditions, 60);
    lv_obj_set_align(ui_conditions, LV_ALIGN_CENTER);
    lv_label_set_text(ui_conditions, "CONDITIONS");

}
